version: "3.8"

services:
  db:
    image: 'postgres:14.3'
    environment:
      POSTGRES_DB: pokemon-app-db
      POSTGRES_USER: pokemon-app
      POSTGRES_PASSWORD: strong-pass
    ports:
      - "54325:5432"